### PR TITLE
fixed scroll effect of StatsCard

### PR DESCRIPTION
**Pull request by sauravraw**
- Fixed the scroll of StatsCard as it was hovering over the navigation

- added hover effect on StatsCard container 

- added a home redirect link in the travel go logo.

### CODE REVIEW

**Comment by Timmotal** [comment]
> * Fixed the scroll of StatsCard as it was hovering over the navigation
> * added hover effect on StatsCard container

can you kindly send a video or screenshot of this feature you adjusted?

**Comment by sauravraw** [comment]
Hi, So this was the issue
Screenshot 2022-10-18 at 2 40 35 PM

here you can see your card was overlapping on the login navigation

I fixed this in this pr
Screenshot 2022-10-18 at 2 41 17 PM

**Comment by sauravraw** [comment]
> > * Fixed the scroll of StatsCard as it was hovering over the navigation
> > * added hover effect on StatsCard container
> 
> can you kindly send a video or screenshot of this feature you adjusted?

https://github.com/nishant-ai/TravelGo/pull/68#issuecomment-1282069767

**Comment by sauravraw** [comment]
@Timmotal any update regarding this?

**Pull request merged**
